; PlatformIO Project Configuration File
;
; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting
;
; https://docs.platformio.org/page/projectconf.html

[env:mhetesp32devkit]
platform = espressif32
board = mhetesp32devkit
framework = arduino
lib_deps =
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BME680 Library
upload_port = COM3
monitor_port = COM3
